-- Bills table for WSBills read-only lookup app.
create extension if not exists pg_trgm;

create table if not exists public.bills (
  id bigint generated by default as identity primary key,
  connection_number text not null,
  mobile_number text not null,
  name text not null,
  address text not null,
  area_name text not null,
  amount numeric(12, 2) not null default 0,
  is_paid boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists bills_connection_number_idx
  on public.bills (connection_number);

create index if not exists bills_mobile_number_idx
  on public.bills (mobile_number);

create index if not exists bills_name_trgm_idx
  on public.bills using gin (name gin_trgm_ops);

alter table public.bills enable row level security;

drop policy if exists "Allow anon SELECT bills" on public.bills;
create policy "Allow anon SELECT bills"
  on public.bills
  for select
  to anon
  using (true);
